name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make SwiftLint executable
        run: chmod +x scripts/swiftlint

      - name: Install Danger Swift
        uses: danger/swift@3.20.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: ${{ github.workspace }}/scripts:${{ env.PATH }}
        with:
          args: '--failOnErrors'