name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Danger Swift
        uses: danger/swift@3.20.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/run-danger.sh https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --verbose
        with:
          args: '--failOnErrors'