name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Danger Swift
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}